/**
 * Utility functions for prompt processing
 */

/**
 * Clean and sanitize user prompt
 * Removes formatting characters, extra whitespace, and unnecessary instructions
 */
export function cleanUserPrompt(prompt: string): string {
  if (!prompt) return '';
  
  let cleaned = prompt.trim();
  
  // Remove common formatting characters that might be copied from enhanced prompts
  cleaned = cleaned
    // Remove box drawing characters
    .replace(/[╔╗╚╝║═]/g, '')
    // Remove escape sequences
    .replace(/\\n/g, '\n')
    .replace(/\\t/g, '\t')
    // Remove excessive newlines (more than 2 consecutive)
    .replace(/\n{3,}/g, '\n\n')
    // Remove leading/trailing whitespace from each line
    .split('\n')
    .map(line => line.trim())
    .filter(line => line.length > 0)
    .join('\n');
  
  // Remove common instruction prefixes that might be copied
  const instructionPrefixes = [
    /^📝\s*USER\s*PROMPT[:\s]*/i,
    /^⚠️⚠️⚠️\s*CRITICAL[:\s]*/i,
    /^📖\s*STORY\s*CONTINUATION[:\s]*/i,
    /^🎨\s*TECHNICAL\s*SPECIFICATIONS[:\s]*/i,
    /^🔞\s*CONTENT\s*POLICY[:\s]*/i,
    /^⚠️\s*ENGLISH\s*TEXT\s*ACCURACY[:\s]*/i,
    /^MANGA\s*PAGE\s*GENERATION\s*REQUEST[:\s]*/i,
  ];
  
  instructionPrefixes.forEach(regex => {
    cleaned = cleaned.replace(regex, '');
  });
  
  // Remove very long instruction blocks (likely copied from enhanced prompt)
  // If prompt is extremely long (>500 chars) and contains many instruction keywords, extract just the user part
  if (cleaned.length > 500) {
    const instructionKeywords = [
      'CRITICAL', 'REQUIREMENTS', 'MUST', 'SHOULD', 'CHARACTER CONSISTENCY',
      'TEXT ACCURACY', 'PANEL LAYOUT', 'STORY CONTINUITY', 'VISUAL REFERENCE',
      'TECHNICAL SPECIFICATIONS', 'CONTENT POLICY', 'DIALOGUE', 'COMPOSITION'
    ];
    
    const instructionCount = instructionKeywords.reduce((count, keyword) => {
      return count + (cleaned.toUpperCase().includes(keyword) ? 1 : 0);
    }, 0);
    
    // If too many instruction keywords, try to extract just the user's actual prompt
    if (instructionCount > 5) {
      // Try to find the actual user prompt part (usually shorter, more natural language)
      const lines = cleaned.split('\n');
      const userLines: string[] = [];
      
      for (const line of lines) {
        const upperLine = line.toUpperCase();
        // Skip lines that look like instructions
        if (
          upperLine.includes('CRITICAL') ||
          upperLine.includes('MUST') ||
          upperLine.includes('REQUIREMENTS') ||
          upperLine.includes('⚠️') ||
          upperLine.includes('✓') ||
          upperLine.includes('✗') ||
          upperLine.includes('STEP') ||
          upperLine.includes('CHECKLIST') ||
          line.length > 200 // Very long lines are likely instructions
        ) {
          continue;
        }
        // Keep shorter, more natural lines
        if (line.length < 200 && line.trim().length > 0) {
          userLines.push(line);
        }
      }
      
      if (userLines.length > 0) {
        cleaned = userLines.join('\n').trim();
      }
    }
  }
  
  // Final cleanup
  cleaned = cleaned
    .trim()
    // Remove excessive spaces
    .replace(/\s+/g, ' ')
    // Remove multiple consecutive newlines
    .replace(/\n{3,}/g, '\n\n');
  
  return cleaned;
}

/**
 * Check if prompt is a user-provided prompt (not auto-generated)
 */
export function isUserProvidedPrompt(prompt: string | undefined | null): boolean {
  if (!prompt || !prompt.trim()) return false;
  
  const trimmed = prompt.trim();
  
  // Auto-generated prompts
  const autoGeneratedPatterns = [
    /^Continue the story naturally/i,
    /^📖\s*(STORY|BATCH)\s*CONTINUATION/i,
    /^Continue the story naturally from page/i,
  ];
  
  // Check if it matches auto-generated patterns
  for (const pattern of autoGeneratedPatterns) {
    if (pattern.test(trimmed)) {
      return false;
    }
  }
  
  // If it's very long and contains many instruction keywords, it's likely copied
  if (trimmed.length > 500) {
    const instructionKeywords = [
      'CRITICAL', 'REQUIREMENTS', 'MUST', 'CHARACTER CONSISTENCY',
      'TEXT ACCURACY', 'PANEL LAYOUT', 'STORY CONTINUITY'
    ];
    
    const keywordCount = instructionKeywords.reduce((count, keyword) => {
      return count + (trimmed.toUpperCase().includes(keyword) ? 1 : 0);
    }, 0);
    
    // Too many instruction keywords = likely copied, not user prompt
    if (keywordCount > 3) {
      return false;
    }
  }
  
  return true;
}

/**
 * Extract the core user intent from a potentially messy prompt
 */
export function extractUserIntent(prompt: string): string {
  const cleaned = cleanUserPrompt(prompt);
  
  // If cleaned prompt is still very long, try to extract the first meaningful sentence
  if (cleaned.length > 300) {
    const sentences = cleaned.split(/[.!?]\s+/);
    if (sentences.length > 0 && sentences[0].length < 200) {
      return sentences[0].trim();
    }
    
    // Otherwise, take first 200 characters
    return cleaned.substring(0, 200).trim();
  }
  
  return cleaned;
}

